// lib/mock-data.ts

import { Scan } from "@/components/dashboard/columns";

export const mockScans: Scan[] = [
  {
    id: "1",
    scanName: "Web App Servers",
    type: "Greybox",
    status: "completed",
    progress: 100,
    vulnerability: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: "2",
    scanName: "Web App Servers",
    type: "Greybox",
    status: "completed",
    progress: 100,
    vulnerability: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: "3",
    scanName: "Web App Servers",
    type: "Greybox",
    status: "completed",
    progress: 100,
    vulnerability: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: "4",
    scanName: "Web App Servers",
    type: "Greybox",
    status: "completed",
    progress: 100,
    vulnerability: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: "5",
    scanName: "Web App Servers",
    type: "Greybox",
    status: "completed",
    progress: 100,
    vulnerability: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: "6",
    scanName: "Web App Servers",
    type: "Greybox",
    status: "completed",
    progress: 100,
    vulnerability: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: "7",
    scanName: "Web App Servers",
    type: "Greybox",
    status: "completed",
    progress: 100,
    vulnerability: { critical: 5, high: 12, medium: 23, low: 18 },
    lastScan: "4d ago",
  },
  {
    id: "8",
    scanName: "Web App Servers",
    type: "Greybox",
    status: "scheduled",
    progress: 100,
    vulnerability: { critical: 5, high: 12, medium: 0, low: 0 },
    lastScan: "4d ago",
  },
  {
    id: "9",
    scanName: "Web App Servers",
    type: "Greybox",
    status: "scheduled",
    progress: 100,
    vulnerability: { critical: 5, high: 12, medium: 0, low: 0 },
    lastScan: "4d ago",
  },
  {
    id: "10",
    scanName: "IoT Devices",
    type: "Blackbox",
    status: "failed",
    progress: 10,
    vulnerability: { critical: 2, high: 4, medium: 8, low: 1 },
    lastScan: "3d ago",
  },
  {
    id: "11",
    scanName: "Temp Data",
    type: "Blackbox",
    status: "failed",
    progress: 10,
    vulnerability: { critical: 2, high: 4, medium: 8, low: 1 },
    lastScan: "3d ago",
  },
];
